[package]
name = "tcp_scan"
version = "0.1.1"
authors = ["Travis Phillips"]
edition = "2021"

[dependencies]
clap = { version = "2.33.0", optional = false }

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"